baseURL: ''
title: 'Ponzela Design'
defaultContentLanguage: 'en'

permalinks:
  posts: "/:sections/:title"

params:
  author: 'Ponzela Design'
  avatar: 'me.png'
  description: 'Designing your vision into reality'
  logo: 'logo.png'
  socials:

    - icon: 'fab fa-instagram fa-lg'
      url: 'https://www.instagram.com/mariaponzela/'

    - icon: 'fab fa-behance fa-lg'
      url: 'https://www.behance.net/mariamoreno17'

    - icon: 'fab fa-linkedin-in fa-lg'
      url: 'https://www.linkedin.com/in/mariaponzela/'

    - icon: 'fab fa-github fa-lg'
      url: 'https://github.com/ponzeladesign'

    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:contact@ponzeladesign.com'

menu:
  main:
    - name: 'Projects'
      url: /projects/
      weight: 1
    - name: 'Contact'
      url: /contact/
      weight: 2
    - name: 'About'
      url: /about/
      weight: 3

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
